### ISSUE TITLE
Add instructions on how to configure this on cloud instances

### ISSUE THREAD

**Issue by andrei-ivanov** [shopware/SwagShopwarePwa#103]
AFAIS, the current instructions only refer to on-premise instances and I don't see how to configure this on cloud instances.

**Comment by elkmod** [comment]
Hi @andrei-ivanov - it is correct, the instructions only refer to self-hosted Shopware instances. Shopware PWA is not working on cloud instances without modifications. Instead, check out [shopware/frontends](https://github.com/shopware/frontends) which is built for Shopware Cloud and follow a very similar approach.
